// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yhwdlyhkqfvqdllhdanw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlod2RseWhrcWZ2cWRsbGhkYW53Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ1NTI0NjIsImV4cCI6MjA2MDEyODQ2Mn0.8d2hb2alcUOG3SE7uqMBKuz53Rj0SCdkmdB0LRm26l4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);