// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nkwhitfyzfhnscwnzuvf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5rd2hpdGZ5emZobnNjd256dXZmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUxNTkzMTMsImV4cCI6MjA2MDczNTMxM30.os1exrMEuTuegVPRXQXX4pYEiUv3JNN7134TLomIrrQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);